# Generated by Django 5.2.1 on 2025-05-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_charityevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='e.g. Wedding Client', max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='teambuildingitem',
            options={'ordering': ['title']},
        ),
        migrations.RemoveField(
            model_name='galleryitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='teambuildingitem',
            name='order',
        ),
    ]
