# Generated by Django 5.2.1 on 2025-05-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testimonial_alter_galleryitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={},
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='content',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='role',
            field=models.CharField(blank=True, help_text='e.g. Wedding Client', max_length=100),
        ),
    ]
